"""add_awards_achievements_notifications_tables

Revision ID: 60380a1dd4a0
Revises: 217ee9c1103f
Create Date: 2025-10-04 17:37:48.534114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60380a1dd4a0'
down_revision: Union[str, Sequence[str], None] = '217ee9c1103f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sliders_id'))

    op.drop_table('sliders')
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_id'))

    op.drop_table('banners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('link_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banners_id'), ['id'], unique=False)

    op.create_table('sliders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('button_text', sa.VARCHAR(), nullable=True),
    sa.Column('button_link', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sliders_id'), ['id'], unique=False)

    # ### end Alembic commands ###
