"""Add youtube_link column to stores table

Revision ID: 6c6b7a0f7c38
Revises: 19a31d9bc5fb
Create Date: 2025-10-04 16:20:19.128483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6b7a0f7c38'
down_revision: Union[str, Sequence[str], None] = '19a31d9bc5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
