"""Removed reqired

Revision ID: 82f56b6d9575
Revises: d3a97b66b7c9
Create Date: 2025-10-09 17:15:14.260827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f56b6d9575'
down_revision: Union[str, Sequence[str], None] = 'd3a97b66b7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('preferred_store',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('preferred_date_time',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.alter_column('preferred_date_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('preferred_store',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
