"""Add subject field to contact_enquiries

Revision ID: b6018b39d965
Revises: 60380a1dd4a0
Create Date: 2025-10-06 11:57:30.736895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6018b39d965'
down_revision: Union[str, Sequence[str], None] = '60380a1dd4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_enquiries', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
