"""Add Vision model and table

Revision ID: d3ab32cfe27b
Revises: 6c6b7a0f7c38
Create Date: 2025-10-04 16:54:38.209373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ab32cfe27b'
down_revision: Union[str, Sequence[str], None] = '6c6b7a0f7c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
